name: Build WASM Examples

on:
  push:
  workflow_dispatch:

jobs:
  webgpu-examples:
    name: Build WebGPU Examples
    runs-on: macos-latest
    steps:
      - name: Checkout Bevy latest tag
        uses: actions/checkout@master
        with:
          repository: 'bevyengine/bevy'
          ref: 'latest'

      - name: Install WASM tooling
        run: |
          cargo install --force wasm-bindgen-cli
          mkdir ./binaryen
          wget -qO- https://github.com/WebAssembly/binaryen/releases/download/version_114/binaryen-version_114-x86_64-macos.tar.gz | tar xvz --strip-components 1 -C ./binaryen binaryen-version_114

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          target: wasm32-unknown-unknown,x86_64-apple-darwin

      - name: Build WASM Examples
        run: |
          export PATH=$PATH:`pwd`/binaryen/bin
          cargo run -p example-showcase -- build-web-gpu-examples --content-folder webgpus --website-hacks --optimize-size
