name: Build WASM Examples

on:
  push:
  workflow_dispatch:

jobs:
  webgpu-examples:
    name: Build WebGPU Examples
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          repository: 'bevyengine/bevy'
          ref: 'latest'

      - name: Install Dependencies
        run: |
          cargo install --force wasm-bindgen-cli
          mkdir ./binaryen
          wget -qO- https://github.com/WebAssembly/binaryen/releases/download/version_114/binaryen-version_114-x86_64-linux.tar.gz | tar xvz -C ./binaryen binaryen-version_114 --strip=1

      - uses: dtolnay/rust-toolchain@stable
        name: Setup Rust
        with:
          target: wasm32-unknown-unknown,x86_64-unknown-linux-gnu

      - name: Build WASM Examples
        run: |
          export PATH=$PATH:`pwd`/binaryen/bin
          cargo run -p example-showcase -- build-web-gpu-examples --content-folder webgpus --website-hacks --optimize-size