name: Build WASM Examples

on:
  push:
  workflow_dispatch:

jobs:
  webgpu-examples:
    name: Build WebGPU Examples
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # if all examples are not built, add a new page here
        page: [0, 1, 2]
        api: [webgl2, webgpu]
    steps:
      - name: Checkout Bevy latest tag
        uses: actions/checkout@master
        with:
          repository: 'mockersf/bevy'
          ref: 'example-showcase-improvements'

      - name: Install WASM tooling
        run: |
          cargo install --force wasm-bindgen-cli
          mkdir ./binaryen
          wget -qO- https://github.com/WebAssembly/binaryen/releases/download/version_114/binaryen-version_114-x86_64-linux.tar.gz | tar xvz -C ./binaryen binaryen-version_114 --strip=1

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          target: wasm32-unknown-unknown,x86_64-unknown-linux-gnu

      - name: Build WASM Examples
        run: |
          export PATH=$PATH:`pwd`/binaryen/bin
          cargo run -p example-showcase -- --per-page 50 --page ${{ matrix.page }} build-wasm-examples --content-folder wasm-examples --api ${{ matrix.api }} --website-hacks --optimize-size

      - uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.api }}-examples-${{ matrix.page }}
          path: wasm-examples
