name: Update Screenshots

on:
  workflow_dispatch:

env:
  PER_PAGE: 1

jobs:
  take-screenshots:
    name: Take Screenshots
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # if all examples are not built, add a new page here
        page: [0, 1]
    steps:

      - name: Checkout Bevy latest tag
        uses: actions/checkout@master
        with:
          repository: 'bevyengine/bevy'
          ref: 'latest'

      # temporary: fetch tools from main branch
      - name: Checkout Bevy Tools
        uses: actions/checkout@master
        with:
          repository: 'mockersf/bevy'
          ref: 'example-showcase-can-remove-desktop-mode'
          path: 'bevy-tools'
      - name: Copy Bevy tools to latest
        run: |
          rm -rf tools
          cp -r bevy-tools/tools/ tools
          rm -rf bevy-tools

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install Bevy dependencies
        run: |
          sudo apt-get update;
          DEBIAN_FRONTEND=noninteractive sudo apt-get install --no-install-recommends -yq \
            libasound2-dev libudev-dev;

      - name: install xvfb, llvmpipe and lavapipe
        run: |
          sudo apt-get update -y -qq
          sudo add-apt-repository ppa:oibaf/graphics-drivers -y
          sudo apt-get update
          sudo apt install -y xvfb libegl1-mesa libgl1-mesa-dri libxcb-xfixes0-dev mesa-vulkan-drivers

      - name: Take Screenshots
        run: |
          xvfb-run cargo run -p example-showcase -- --page ${{ matrix.page }} --per-page ${{ env.PER_PAGE }} run --screenshot

      - name: Upload Generated Files
        uses: actions/upload-artifact@v3
        with:
          name: screenshots-${{ matrix.page }}
          path: screenshots

  prepare-pr:
    name: Prepare Screenshots Update PR
    runs-on: ubuntu-latest
    needs: take-screenshots
    permissions:
      pull-requests: write
    steps:
      
      - name: Clone bevy-website repo
        uses: actions/checkout@master

      - name: Download all artifacts
        uses: actions/download-artifact@v3

      - name: Move examples to the correct folder
        run: |
          rm -rf static/screenshots
          mkdir static/screenshots
          for file in screenshots-*
          do
            rsync -a $file/* static/screenshots/
            rm -rf $file
          done

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          delete-branch: true
          title: Update Examples Screenshots
          branch-suffix: random

  fast-pr:
    name: Fast PR
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      
      - name: Clone bevy-website repo
        uses: actions/checkout@master

      - name: Move examples to the correct folder
        run: |
          rm -rf static/screenshots

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          delete-branch: true
          title: Fast
          branch-suffix: random
